### ISSUE TITLE
Issue after upgrade to Laravel 10

### ISSUE THREAD

**Issue by mvdgeijn** [diglactic/laravel-breadcrumbs#64] opened 2023-03-31 14:38 UTC
I've upgraded my project to Laravel 10 today, but now my route bound parameters are messed up. For some unknown reason, there is an extra null parameter passed into the closure and therefor have to add an extra unused parameter to the closure.

**Working laravel 9 code in the breadcrumbs.php file:**

`Breadcrumbs::for('account.show', function (BreadcrumbTrail $trail, App\Models\Account $account ) {
    $trail->parent('dashboard.index');
    $trail->push('Account ' . $account->account_nr, route('account.show', $account ));
});`

**Working laravel 10 code in the breadcrumbs.php file:**

`Breadcrumbs::for('account.show', function (BreadcrumbTrail $trail, $empty, App\Models\Account $account ) {
    $trail->parent('dashboard.index');
    $trail->push('Account ' . $account->account_nr, route('account.show', $account ));
});`

The $empty parameter is assigned null, and the $account parameter contains the expected model. I'm debugging this for an hour now, but maybe somebody has run into something similar.

**Comment by mvdgeijn** [comment] 2023-03-31 15:04
I have not checked what the difference is between laravel 9 and laravel 10, but I figured it out what the cause is:

In Manager.php:253 the route parameters are retrieved from the current route. But in our project one of the two parameters is removed using $request->route()->forgetParameter(). That "forgotten" parameter is present in the $route->parameterNames property, but it isn't in the $route->parameters property.

I'm not sure if this is a difference between Laravel 9 and Laravel 10 (bug?), but it could be fixed in this repository by the following code at Manager.php:253:

$params = array_values( $route->parameters );

**Comment by shengslogar** [comment] 2023-03-31 16:26
What versions of this package did you use before/after you upgraded Laravel?

**Comment by mvdgeijn** [comment] 2023-03-31 17:32
I was just checking that out. I was using version 7.2 before the upgrade, 8.1 after the upgrade.

When I checked v7.2 Manager.php:245. There is the line I was suggesting:

`$params = array_values($route->parameters());`

In version v8.1 Manager.php:253:

`        $params = array_values(array_map(function ($parameterName) use ($route) {
            return $route->parameter($parameterName);
        }, $route->parameterNames()));`

**Comment by shengslogar** [comment] 2023-03-31 17:46
See release notes on [v8.0.0](https://github.com/diglactic/laravel-breadcrumbs/releases/tag/v8.0.0). There is indeed a breaking change that prefers parameters as defined in a route signature over parameters mutated by middleware.

This is desired behavior for Breadcrumbs at this point. [An iterative option is doing something like what Laravel does on controller methods and reflecting on variable names](https://github.com/diglactic/laravel-breadcrumbs/pull/52#issuecomment-1195079809), but I'm not sure of the implications and that seems like an edge case. You could also look at creating a custom macro to restore functionality from past versions.

I would love to learn more about your use case if you have the time and would certainly welcome more discussion + a PR, but I'm going to close this ticket out for now since this is expected behavior.

**Closed by shengslogar** 2023-03-31 17:46 UTC
Labels: needsmoreinfo
